### ISSUE TITLE
getting JSON parse error while running npm audit

### ISSUE THREAD

**Issue by shiv0808** [bpedroza/js-pkce#16]
Hi , i have implemented single sign on in my application using js-pkce library.The code works fine for me. But i tried running npm audit over the application just to check for any vulnerabilities in the library. Here is the error which i encountered on **npm audit** :

npm ERR! Unexpected end of JSON input while parsing near ''

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ssriv112\AppData\Roaming\npm-cache\_logs\2022-02-16T11_47_24_273Z-debug.log

and the log file says that these are the target files having errors :
verbose stack SyntaxError: Unexpected end of JSON input while parsing near ''
**- verbose stack     at JSON.parse (<anonymous>)
- verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
- verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
- verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)**

It would be great if there are any solutions to handle this issue.Attaching "\json-parse-better-errors\index.js" file for your reference
[index.js.txt](https://github.com/bpedroza/js-pkce/files/8079650/index.js.txt).

**Comment by bpedroza** [comment]
None of those paths are part of this repository. Please open you issue with the json-parse-better-errors repository if that is the one causing this issue..
